### ISSUE TITLE
Error in running the test file given with this tool

### ISSUE THREAD

**Issue by dhwani2410** [ifishlin/HAHap#1]
This was the command line used for running the HAHap tool:-
python HAHap phase HG002_heter.vcf HG002.hs37d5.2x250.bam phased.vcf

This is the error i got
=== Build Connected Component ===
Traceback (most recent call last):
  File "HAHap", line 9, in <module>
    main()
  File "/home/dhwani/Documents/softwares/HAHap/HAHap/__main__.py", line 73, in main
    module.main(args)
  File "/home/dhwani/Documents/softwares/HAHap/HAHap/phase.py", line 63, in main
    connected_component = blocks_main(args, str(chrom), var_loc, timer)
  File "/home/dhwani/Documents/softwares/HAHap/HAHap/blocks.py", line 136, in main
    samfile = pysam.AlignmentFile(args.bam_file, "rb")
  File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 629, in pysam.libcalignmentfile.AlignmentFile._open
  File "pysam/libchtslib.pyx", line 364, in pysam.libchtslib.HTSFile.check_truncation
OSError: no BGZF EOF marker; file may be truncated

**Comment by ifishlin** [comment]
It seems the bam file was broken. You can re-download it or check the md5sum for sure.
